### ISSUE TITLE
[BF4] spectators

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#108]
Now that BF4 has a spectator mode, the B3 bf4 parser needs to handle it correctly.
## TODO
- [x] correctly assign the value of `client.team` to `b3.TEAM_SPEC` to players in spectator mode. This is particularly important for plugins doing team balancing, etc. In the _bf4.py_ file, see method `getTeam`.
- [ ] make sure `client.team` is correct when B3 starts and a player is already in spectator mode
- [ ] make sure `client.team` is correct when a player joins the server straight in spectator mode
- [ ] make sure `client.team` is correctly changed when a player moves from/to spectator mode

---

depends: #97
